########## Testcase 0: Failed ##########
Expected Output: 
Yes
Your Output: 
Exception in thread "main" java.lang.NullPointerException
	at Ransom.put(Solution.java:55)
	at Solution.main(Solution.java:127)
----------------------------------------
########## Testcase 1: Failed ##########
Expected Output: 
No
Your Output: 
Exception in thread "main" java.lang.NullPointerException
	at Ransom.put(Solution.java:55)
	at Solution.main(Solution.java:127)
----------------------------------------
########## Testcase 2: Failed ##########
Expected Output: 
No
Your Output: 
Exception in thread "main" java.lang.NullPointerException
	at Ransom.put(Solution.java:55)
	at Solution.main(Solution.java:127)
----------------------------------------
########## Testcase 3: Failed ##########
Expected Output: 
No
Your Output: 
Exception in thread "main" java.lang.NullPointerException
	at Ransom.put(Solution.java:55)
	at Solution.main(Solution.java:127)
----------------------------------------
########## Testcase 4: Failed ##########
Expected Output: 
Yes
Your Output: 
Exception in thread "main" java.lang.NullPointerException
	at Ransom.put(Solution.java:55)
	at Solution.main(Solution.java:127)
----------------------------------------
########## Testcase 5: Failed ##########
Expected Output: 
Yes
Your Output: 
Exception in thread "main" java.lang.NullPointerException
	at Ransom.put(Solution.java:55)
	at Solution.main(Solution.java:127)
----------------------------------------
